"""
Unified initial configuration object for LLM Gateway setup.

Captures ALL choices made during setup in a single file:
  - Component selections (Ollama, llama.cpp, whisper)
  - SSH preferences
  - API keys / secrets
  - Grafana credentials
  - Data directory path

Stored at: <data_dir>/setup-config.yaml
Read by: setup script (to provision), gw script (to filter components).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

import yaml


@dataclass
class SetupConfig:
    """All initial configuration choices from setup."""

    # ── Data directory ────────────────────────────────────────────────────────
    data_dir: str = "~/.llm-gateway"

    # ── Component selections ──────────────────────────────────────────────────
    install_ollama: bool = False
    install_llama_cpp: bool = False
    install_whisper: bool = False

    # ── SSH settings ──────────────────────────────────────────────────────────
    ssh_enable_remote_login: bool = False
    ssh_authorized_key: str = ""

    # ── Secrets / API keys ────────────────────────────────────────────────────
    litellm_master_key: str = ""
    openrouter_api_key: str = ""
    anthropic_api_key: str = ""
    openai_api_key: str = ""
    gemini_api_key: str = ""
    xai_api_key: str = ""
    perplexity_api_key: str = ""

    # ── Grafana ───────────────────────────────────────────────────────────────
    grafana_admin_user: str = "admin"
    grafana_admin_password: str = ""

    # ── Persistence ──────────────────────────────────────────────────────────

    @classmethod
    def load(cls, path: Path) -> SetupConfig:
        """Load from YAML file. Returns defaults if file doesn't exist."""
        if not path.exists():
            return cls()
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except Exception:
            return cls()
        # Only accept known fields (ignore stale keys from older versions)
        known_fields = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known_fields}
        return cls(**filtered)

    def save(self, path: Path) -> None:
        """Write to YAML file. Creates parent directories."""
        path.parent.mkdir(parents=True, exist_ok=True)
        # Don't write secrets to the setup config — those go to .env only.
        # Store just the structural choices.
        safe_data = {
            "data_dir": self.data_dir,
            "install_ollama": self.install_ollama,
            "install_llama_cpp": self.install_llama_cpp,
            "install_whisper": self.install_whisper,
            "ssh_enable_remote_login": self.ssh_enable_remote_login,
            "grafana_admin_user": self.grafana_admin_user,
        }
        path.write_text(
            yaml.dump(safe_data, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass

    # ── Helpers ───────────────────────────────────────────────────────────────

    def selected_components(self) -> list[str]:
        """Return list of selected optional component names."""
        result: list[str] = []
        if self.install_ollama:
            result.append("ollama")
        if self.install_llama_cpp:
            result.append("llama-server")
        if self.install_whisper:
            result.append("whisper-server")
        return result

    def generate_env_file(self, env_example_path: Path, output_path: Path) -> None:
        """
        Generate .env at output_path using .env.example as a template,
        substituting any secrets that were collected during setup.
        """
        # Map config fields → .env variable names
        secrets_map = {
            "LITELLM_MASTER_KEY": self.litellm_master_key,
            "OPENROUTER_API_KEY": self.openrouter_api_key,
            "ANTHROPIC_API_KEY": self.anthropic_api_key,
            "OPENAI_API_KEY": self.openai_api_key,
            "GEMINI_API_KEY": self.gemini_api_key,
            "XAI_API_KEY": self.xai_api_key,
            "PERPLEXITY_API_KEY": self.perplexity_api_key,
            "GF_SECURITY_ADMIN_USER": self.grafana_admin_user,
            "GF_SECURITY_ADMIN_PASSWORD": self.grafana_admin_password,
        }

        if not env_example_path.exists():
            # No template — write a minimal .env with just the collected secrets
            lines = [
                "# LLM Gateway — generated by setup",
                f"LITELLM_MASTER_KEY={self.litellm_master_key or 'sk-gateway-master-change-me'}",
                f"DATABASE_URL=postgresql://litellm:litellm@postgres:5432/litellm",
            ]
            for key, val in secrets_map.items():
                if val and key != "LITELLM_MASTER_KEY":
                    lines.append(f"{key}={val}")
            output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            try:
                os.chmod(output_path, 0o600)
            except OSError:
                pass
            return

        # Read template and substitute values
        lines: list[str] = []
        for line in env_example_path.read_text(encoding="utf-8").splitlines():
            # Preserve comments and blank lines
            stripped = line.strip()
            if stripped.startswith("#") or "=" not in stripped:
                lines.append(line)
                continue

            key = stripped.split("=", 1)[0].strip()
            if key in secrets_map and secrets_map[key]:
                lines.append(f"{key}={secrets_map[key]}")
            else:
                lines.append(line)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        try:
            os.chmod(output_path, 0o600)
        except OSError:
            pass
